/* ---------------- 怪物卡片系統 ---------------- */
/* 自動產生：由 tools/gen_cards_data.js 從 ro_cards_data/cards.json 轉換 */
const CARDS = {
  poring_card: { id: 'poring_card', monsterId: null, name: '圣诞波利卡片', icon: '⚔️', slot: 'weapon', bonus: {"eleDmg_shadow":20}, desc: '對暗屬性魔物傷害+20%' },
  fabre_card: { id: 'fabre_card', monsterId: 'fabre', name: '绿棉虫卡片', icon: '⚔️', slot: 'weapon', bonus: {"vit":1,"hp":100}, desc: 'VIT+1, MaxHP +100' },
  pupa_card: { id: 'pupa_card', monsterId: 'pupa', name: '虫蛹卡片', icon: '🛡️', slot: 'armor', bonus: {"hp":700}, desc: 'MaxHP +700' },
  drops_card: { id: 'drops_card', monsterId: 'drops', name: '土波利卡片', icon: '⚔️', slot: 'weapon', bonus: {"dex":1,"hit":3}, desc: 'DEX+1, HIT+3' },
  lunatic_card: { id: 'lunatic_card', monsterId: 'lunatic', name: '疯兔卡片', icon: '⚔️', slot: 'weapon', bonus: {"luk":1,"critRate":1,"perfectDodge":1}, desc: 'LUK+1, CRI+1, 完全回避+1' },
  picky_card: { id: 'picky_card', monsterId: 'picky_', name: '蛋壳小鸡卡片', icon: '🛡️', slot: 'armor', bonus: {"vit":1,"hp":100}, desc: 'VIT+1, MaxHP +100' },
  chonchon_card: { id: 'chonchon_card', monsterId: 'chonchon', name: '苍蝇卡片', icon: '👢', slot: 'footgear', bonus: {"agi":1,"flee":2}, desc: 'AGI+1, FLEE+2' },
  wilow_card: { id: 'wilow_card', monsterId: 'wilow', name: '树精卡片', icon: '👑', slot: 'headgear', bonus: {"sp":80}, desc: 'MaxSP +80' },
  thief_bug_egg_card: { id: 'thief_bug_egg_card', monsterId: 'thief_bug_egg', name: '盗虫卵卡片', icon: '🛡️', slot: 'shield', bonus: {"hp":400}, desc: 'MaxHP +400' },
  andre_egg_card: { id: 'andre_egg_card', monsterId: 'ant_egg', name: '蚁卵卡片', icon: '🛡️', slot: 'shield', bonus: {"hpPct":5}, desc: 'MaxHP +5%' },
  roda_frog_card: { id: 'roda_frog_card', monsterId: 'roda_frog', name: '罗达蛙卡片', icon: '🛡️', slot: 'armor', bonus: {"hp":400,"sp":50}, desc: 'MaxHP +400, MaxSP +50' },
  condor_card: { id: 'condor_card', monsterId: 'condor', name: '秃鹰卡片', icon: '🧣', slot: 'garment', bonus: {"flee":10}, desc: 'FLEE+10' },
  thief_bug_card: { id: 'thief_bug_card', monsterId: 'thief_bug', name: '盗虫卡片', icon: '🛡️', slot: 'armor', bonus: {"agi":1}, desc: 'AGI+1' },
  andre_larva_card: { id: 'andre_larva_card', monsterId: null, name: '白蚁幼虫卡片', icon: '⚔️', slot: 'weapon', bonus: {"int":1,"sp":10}, desc: 'INT+1, MaxSP +10' },
  hornet_card: { id: 'hornet_card', monsterId: 'hornet', name: '蜂兵卡片', icon: '⚔️', slot: 'weapon', bonus: {"str":1,"atk":3}, desc: 'STR+1, ATK+3' },
  farmiliar_card: { id: 'farmiliar_card', monsterId: 'farmiliar', name: '吸血蝙蝠卡片', icon: '⚔️', slot: 'weapon', bonus: {"atk":5}, desc: '攻击时，有5%的几率使敌人陷入黑暗状态。, ATK+5' },
  rocker_card: { id: 'rocker_card', monsterId: 'rocker', name: '摇滚蝗虫卡片', icon: '🛡️', slot: 'armor', bonus: {"dex":1,"atk":5}, desc: 'DEX+1, ATK+5' },
  spore_card: { id: 'spore_card', monsterId: 'spore', name: '魔菇卡片', icon: '🃏', slot: 'any', bonus: {"vit":2}, desc: 'VIT+2' },
  desert_wolf_babe_card: { id: 'desert_wolf_babe_card', monsterId: 'desert_wolf_b', name: '沙漠幼狼卡片', icon: '🛡️', slot: 'armor', bonus: {"int":1}, desc: 'INT+1' },
  plankton_card: { id: 'plankton_card', monsterId: 'plankton', name: '漂浮虫卡片', icon: '⚔️', slot: 'weapon', bonus: {"atk":5}, desc: '攻击时，有5%的几率使敌人陷入沉睡状态。, ATK+5' },
  skeleton_card: { id: 'skeleton_card', monsterId: 'skeleton', name: '邪骸战士卡片', icon: '⚔️', slot: 'weapon', bonus: {"atk":10}, desc: '攻击时，有2%的几率使敌人陷入眩晕状态。, ATK+10' },
  thief_bug_female_card: { id: 'thief_bug_female_card', monsterId: null, name: '浮勒盗虫卡片', icon: '⚔️', slot: 'weapon', bonus: {"agi":1,"flee":1}, desc: 'AGI+1, FLEE+1' },
  kukre_card: { id: 'kukre_card', monsterId: 'kukre', name: '库克雷卡片', icon: '🃏', slot: 'any', bonus: {"agi":2}, desc: 'AGI+2' },
  tarou_card: { id: 'tarou_card', monsterId: 'tarou', name: '白鼠卡片', icon: '🃏', slot: 'any', bonus: {"str":2}, desc: 'STR+2' },
  wolf_card: { id: 'wolf_card', monsterId: 'wolf', name: '狼卡片', icon: '⚔️', slot: 'weapon', bonus: {"atk":15,"critRate":1}, desc: 'ATK+15, CRI+1' },
  mandragora_card: { id: 'mandragora_card', monsterId: 'mandragora', name: '曼陀罗魔花卡片', icon: '⚔️', slot: 'weapon', bonus: {"eleDmg_wind":20}, desc: '對风屬性魔物傷害+20%' },
  ambernite_card: { id: 'ambernite_card', monsterId: 'ambernite', name: '蜗牛卡片', icon: '🛡️', slot: 'shield', bonus: {"def":2}, desc: 'DEF+2' },
  worm_tail_card: { id: 'worm_tail_card', monsterId: 'worm_tail', name: '森灵卡片', icon: '🃏', slot: 'any', bonus: {"dex":2}, desc: 'DEX+2' },
  snake_card: { id: 'snake_card', monsterId: 'snake', name: '青蛇卡片', icon: '⚔️', slot: 'weapon', bonus: {"atk":5}, desc: '攻击时，有5%的几率使敌人中毒。, ATK+5' },
  stainer_card: { id: 'stainer_card', monsterId: 'stainer', name: '瓢虫卡片', icon: '👑', slot: 'headgear', bonus: {"def":1}, desc: '受到攻击时，被沉默的几率降低20%。, DEF+1' },
  coco_card: { id: 'coco_card', monsterId: 'coco', name: '松鼠卡片', icon: '👑', slot: 'headgear', bonus: {"def":1}, desc: '受到攻击时，被睡眠的几率降低20%。, DEF+1' },
  steel_chonchon_card: { id: 'steel_chonchon_card', monsterId: 'steel_chonchon', name: '绿苍蝇卡片', icon: '🛡️', slot: 'armor', bonus: {"def":2}, desc: 'DEF+2, 受到风属性的伤害减少10%。' },
  andre_card: { id: 'andre_card', monsterId: 'andre', name: '白蚁卡片', icon: '⚔️', slot: 'weapon', bonus: {"atk":20}, desc: 'ATK+20' },
  martin_card: { id: 'martin_card', monsterId: 'martin', name: '土拨鼠卡片', icon: '👑', slot: 'headgear', bonus: {"def":1}, desc: '受到攻击时，被黑暗的几率降低20%。, DEF+1' },
  vadon_card: { id: 'vadon_card', monsterId: 'vadon', name: '螃蟹卡片', icon: '⚔️', slot: 'weapon', bonus: {"eleDmg_fire":20}, desc: '對火屬性魔物傷害+20%' },
  thief_bug_male_card: { id: 'thief_bug_male_card', monsterId: 'thief_bug_', name: '玛勒盗虫卡片', icon: '👢', slot: 'footgear', bonus: {"agi":2}, desc: 'AGI+2' },
  yoyo_card: { id: 'yoyo_card', monsterId: 'yoyo', name: '溜溜猴卡片', icon: '🃏', slot: 'any', bonus: {"perfectDodge":5,"agi":1}, desc: '完全回避+5, AGI+1' },
  elder_wilow_card: { id: 'elder_wilow_card', monsterId: 'elder_wilow', name: '长老树精卡片', icon: '👑', slot: 'headgear', bonus: {"int":2}, desc: 'INT+2' },
  marina_card: { id: 'marina_card', monsterId: 'marina', name: '水母卡片', icon: '⚔️', slot: 'weapon', bonus: {"atk":5}, desc: '攻击时，有5%的几率使敌人陷入冰冻状态。, ATK+5' },
  dustiness_card: { id: 'dustiness_card', monsterId: 'dustiness', name: '猎蝇卡片', icon: '🧣', slot: 'garment', bonus: {"flee":5}, desc: '受到风属性的伤害减少30%。, FLEE+5' },
  metaller_card: { id: 'metaller_card', monsterId: 'metaller', name: '重金属蝗虫卡片', icon: '⚔️', slot: 'weapon', bonus: {"atk":5}, desc: '攻击时，有5%的几率使敌人陷入沉默状态。, ATK+5' },
  cornutus_card: { id: 'cornutus_card', monsterId: 'cornutus', name: '卡那多斯卡片', icon: '🛡️', slot: 'armor', bonus: {"def":1}, desc: '可使铠甲完全不受损。, DEF+1' },
  anacondaq_card: { id: 'anacondaq_card', monsterId: 'anacondaq', name: '黄蛇卡片', icon: '⚔️', slot: 'weapon', bonus: {"eleDmg_poison":20}, desc: '對毒屬性魔物傷害+20%' },
  zerom_card: { id: 'zerom_card', monsterId: 'zerom', name: '杰洛米卡片', icon: '🃏', slot: 'any', bonus: {"dex":3}, desc: 'DEX+3' },
  kaho_card: { id: 'kaho_card', monsterId: 'kaho', name: '卡浩卡片', icon: '⚔️', slot: 'weapon', bonus: {"eleDmg_earth":20}, desc: '對地屬性魔物傷害+20%' },
  megalodon_card: { id: 'megalodon_card', monsterId: 'megalodon', name: '邪骸食人鱼卡片', icon: '🛡️', slot: 'shield', bonus: {"def":1}, desc: '受到攻击时，被冰冻的几率降低20%。, DEF+1' },
  drainliar_card: { id: 'drainliar_card', monsterId: 'drainliar', name: '红蝙蝠卡片', icon: '⚔️', slot: 'weapon', bonus: {"eleDmg_water":20}, desc: '對水屬性魔物傷害+20%' },
  orc_zombie_card: { id: 'orc_zombie_card', monsterId: 'orc_zombie', name: '兽人腐尸卡片', icon: '🧣', slot: 'garment', bonus: {"flee":5}, desc: '受到不死系魔物的伤害减少30%。, FLEE+5' },
  golem_card: { id: 'golem_card', monsterId: 'golem', name: '巨石怪卡片', icon: '⚔️', slot: 'weapon', bonus: {"atk":5}, desc: '可使武器完全不受损。, ATK+5' },
  argos_card: { id: 'argos_card', monsterId: 'argos', name: '艾斯蜘蛛卡片', icon: '🛡️', slot: 'shield', bonus: {"def":1}, desc: '受到攻击时，被石化的几率降低20%。, DEF+1' },
  magnolia_card: { id: 'magnolia_card', monsterId: 'magnolia', name: '魔锅蛋卡片', icon: '⚔️', slot: 'weapon', bonus: {"atk":5}, desc: '攻击时，有5%的几率使敌人陷入受诅咒的状态。, ATK+5' },
  savage_card: { id: 'savage_card', monsterId: 'savage', name: '野猪卡片', icon: '🛡️', slot: 'armor', bonus: {"vit":3}, desc: 'VIT+3' },
  mantis_card: { id: 'mantis_card', monsterId: 'mantis', name: '螳螂卡片', icon: '🃏', slot: 'any', bonus: {"str":3}, desc: 'STR+3' },
  hode_card: { id: 'hode_card', monsterId: 'hode', name: '蚯蚓卡片', icon: '🧣', slot: 'garment', bonus: {"flee":5}, desc: '受到地属性的伤害减少30%。, FLEE+5' },
  desert_wolf_card: { id: 'desert_wolf_card', monsterId: 'desert_wolf', name: '沙漠之狼卡片', icon: '⚔️', slot: 'weapon', bonus: {"atk":5}, desc: '对小型魔物增加15%的伤害。, ATK+5' },
  orc_skeleton_card: { id: 'orc_skeleton_card', monsterId: 'orc_skeleton', name: '邪骸兽人卡片', icon: '⚔️', slot: 'weapon', bonus: {"eleDmg_holy":20}, desc: '對圣屬性魔物傷害+20%' },
  soldier_skeleton_card: { id: 'soldier_skeleton_card', monsterId: 'soldier_skeleton', name: '邪骸士兵卡片', icon: '⚔️', slot: 'weapon', bonus: {"critRate":9}, desc: 'CRI+9' },
  sword_fish_card: { id: 'sword_fish_card', monsterId: 'sword_fish', name: '异变鱼卡片', icon: '🛡️', slot: 'armor', bonus: {"def":1}, desc: '可将铠甲的属性转变为水属性。, DEF+1' },
  munak_card: { id: 'munak_card', monsterId: 'munak', name: '僵尸卡片', icon: '🛡️', slot: 'shield', bonus: {"def":1}, desc: '受到攻击时，被石化的几率降低15%。, 受到地属性的伤害减少5%。, DEF+1' },
  kobold_card: { id: 'kobold_card', monsterId: 'kobold_1', name: '犬妖卡片', icon: '🃏', slot: 'any', bonus: {"critRate":4,"str":1}, desc: 'CRI+4, STR+1' },
  skel_worker_card: { id: 'skel_worker_card', monsterId: 'skel_worker', name: '邪骸矿工卡片', icon: '⚔️', slot: 'weapon', bonus: {"atk":5}, desc: '对中型魔物增加15%的伤害。, ATK+5' },
  zenorc_card: { id: 'zenorc_card', monsterId: 'zenorc', name: '兹诺克卡片', icon: '⚔️', slot: 'weapon', bonus: {"atk":10}, desc: '攻击时，有4%的几率使敌人中毒。, ATK+10' },
  matyr_card: { id: 'matyr_card', monsterId: 'matyr', name: '黑狐卡片', icon: '👢', slot: 'footgear', bonus: {"hpPct":10,"agi":1}, desc: 'MaxHP +10%, AGI+1' },
  dokebi_card: { id: 'dokebi_card', monsterId: 'dokebi', name: '土人卡片', icon: '🛡️', slot: 'armor', bonus: {"def":1}, desc: '可将铠甲的属性转变为风属性。, DEF+1' },
  pasana_card: { id: 'pasana_card', monsterId: 'pasana', name: '帕莎纳卡片', icon: '🛡️', slot: 'armor', bonus: {"def":1}, desc: '可将铠甲的属性转变为火属性。, DEF+1' },
  sohee_card: { id: 'sohee_card', monsterId: 'sohee', name: '鬼女卡片', icon: '👢', slot: 'footgear', bonus: {"spPct":15}, desc: 'MaxSP +15%, SP恢复力提高3%' },
  sand_man_card: { id: 'sand_man_card', monsterId: 'sand_man', name: '泥人卡片', icon: '🛡️', slot: 'armor', bonus: {"def":1}, desc: '可将铠甲的属性转变为地属性。, DEF+1' },
  whisper_card: { id: 'whisper_card', monsterId: 'whisper', name: '白幽灵卡片', icon: '🧣', slot: 'garment', bonus: {"flee":20}, desc: '受念属性魔物攻击时，+50%的伤害。, FLEE+20' },
  mummy_card: { id: 'mummy_card', monsterId: 'mummy', name: '木乃伊卡片', icon: '⚔️', slot: 'weapon', bonus: {"hit":20}, desc: 'HIT+20' },
  myst_card: { id: 'myst_card', monsterId: 'myst', name: '麦斯特卡片', icon: '🧣', slot: 'garment', bonus: {"flee":5}, desc: '受到毒属性的伤害减少30%。, FLEE+5' },
  jakk_card: { id: 'jakk_card', monsterId: 'jakk', name: '南瓜先生卡片', icon: '🧣', slot: 'garment', bonus: {"flee":5}, desc: '受到火属性的伤害减少30%。, FLEE+5' },
  marionette_card: { id: 'marionette_card', monsterId: 'marionette', name: '傀儡娃娃卡片', icon: '🧣', slot: 'garment', bonus: {"flee":5}, desc: '受到念属性的伤害减少30%。, FLEE+5' },
  argiope_card: { id: 'argiope_card', monsterId: 'argiope', name: '艾吉欧蜈蚣卡片', icon: '🛡️', slot: 'armor', bonus: {"def":1}, desc: '可将铠甲的属性转变为毒属性。, DEF+1' },
  isis_card: { id: 'isis_card', monsterId: 'isis', name: '蛇女伊丝卡片', icon: '🧣', slot: 'garment', bonus: {"flee":5}, desc: '受到暗属性的伤害减少30%。, FLEE+5' },
  phreeoni_card: { id: 'phreeoni_card', monsterId: 'phreeoni', name: '皮里恩卡片', icon: '⚔️', slot: 'weapon', bonus: {"hit":100}, desc: 'HIT+100' },
  deviruchi_card: { id: 'deviruchi_card', monsterId: 'deviruchi', name: '小恶魔卡片', icon: '👑', slot: 'headgear', bonus: {"str":1}, desc: '可避免陷入黑暗的状态。, STR+1' },
  minorous_card: { id: 'minorous_card', monsterId: 'minorous', name: '米洛斯卡片', icon: '⚔️', slot: 'weapon', bonus: {"atk":5}, desc: '对大型魔物增加15%的伤害。, ATK+5' },
  nightmare_card: { id: 'nightmare_card', monsterId: null, name: '梦魇卡片', icon: '👑', slot: 'headgear', bonus: {"agi":1}, desc: '可避免陷入睡眠的状态。, AGI+1' },
  baphomet_card: { id: 'baphomet_card', monsterId: 'baphomet_', name: '小巴风特卡片', icon: '🧣', slot: 'garment', bonus: {"agi":3,"critRate":1}, desc: 'AGI+3, CRI+1' },
  evil_druid_card: { id: 'evil_druid_card', monsterId: 'evil_druid', name: '闇神官卡片', icon: '🛡️', slot: 'armor', bonus: {"int":1,"def":1}, desc: '可将铠甲的属性转变为不死属性。, INT+1, DEF+1' },
  orc_hero_card: { id: 'orc_hero_card', monsterId: 'ork_hero', name: '兽人英雄卡片', icon: '👑', slot: 'headgear', bonus: {"vit":3}, desc: '可完全避免陷入眩晕的状态。, VIT+3' },
  crab_card: { id: 'crab_card', monsterId: 'crab', name: '卡拉蟹卡片', icon: '⚔️', slot: 'weapon', bonus: {"eleDmg_water":30}, desc: '对海星的伤害增加30%，ATK+5, 卡拉蟹、贝壳魔灵、海星卡片全部装备后，击杀鱼贝类魔物时，有30%的几率会掉落生鱼片。, 對水屬性魔物傷害+30%' },
  nine_tail_card: { id: 'nine_tail_card', monsterId: 'nine_tail', name: '九尾狐卡片', icon: '🃏', slot: 'any', bonus: {"agi":2}, desc: 'AGI+2, 精炼9以上时，FLEE+20。' },
  antique_firelock_card: { id: 'antique_firelock_card', monsterId: 'antique_firelock', name: '武士火枪兵卡片', icon: '👢', slot: 'footgear', bonus: {"str":2}, desc: 'STR+2, 精炼9以上时，MAXHP+10%，MAXSP+10%' },
  dragon_fly_card: { id: 'dragon_fly_card', monsterId: 'dragon_fly', name: '龙蝇卡片', icon: '🃏', slot: 'any', bonus: {"agi":1}, desc: 'AGI+1, 装备苍蝇卡片时，FLEE+18' },
  vagabond_wolf_card: { id: 'vagabond_wolf_card', monsterId: 'vagabond_wolf', name: '流浪之狼卡片', icon: '🃏', slot: 'any', bonus: {"str":1}, desc: 'STR+1, 装备狼卡片时，FLEE+18' },
  mysteltainn_card: { id: 'mysteltainn_card', monsterId: 'mysteltainn', name: '弒神者卡片', icon: '🛡️', slot: 'shield', bonus: {"def":1}, desc: '受到小型魔物的伤害会减少25%。, DEF+1' },
  miyabi_ningyo_card: { id: 'miyabi_ningyo_card', monsterId: 'miyabi_ningyo', name: '米雅毕卡片', icon: '👢', slot: 'footgear', bonus: {"spPct":10}, desc: 'MaxSP +10%, 冰冻术的伤害，增加5%。' },
  stalactic_golem_card: { id: 'stalactic_golem_card', monsterId: 'stalactic_golem', name: '钟乳巨石怪卡片', icon: '🃏', slot: 'any', bonus: {"def":1}, desc: 'DEF+1, 受到攻击时，被眩晕的几率降低20%。' },
  sting_card: { id: 'sting_card', monsterId: 'sting', name: '史汀卡片', icon: '🛡️', slot: 'shield', bonus: {"def":2}, desc: 'DEF+2, 精炼9以上时，MDEF+5' },
  c_tower_manager_card: { id: 'c_tower_manager_card', monsterId: 'c_tower_manager', name: '钟塔守护者卡片', icon: '🃏', slot: 'any', bonus: {"int":1}, desc: 'INT+1, 技能变动咏唱时间减少5%。钟怪、古钟魔、朽魔卡片一起装备时，MDEF+3，DEF+3。' },
  shinobi_card: { id: 'shinobi_card', monsterId: 'shinobi', name: '火忍西怒毕卡片', icon: '🃏', slot: 'any', bonus: {"agi":1}, desc: 'AGI+1, 受到物理伤害时，可使用伪装5技能。, 若没有练到伪装3级而装备时，要靠着墙壁时才会启动的。' },
  baby_leopard_card: { id: 'baby_leopard_card', monsterId: 'baby_leopard', name: '小花豹卡片', icon: '🃏', slot: 'any', bonus: {"luk":3}, desc: 'LUK+3, 当商人系列角色装备时，铠甲是不会受破损的。' },
  archangeling_card: { id: 'archangeling_card', monsterId: 'archangeling', name: '圣天使波利卡片', icon: '🃏', slot: 'any', bonus: {"hp":300}, desc: 'MaxHP +300, LUK77以上时，HP恢复力和SP恢复力上升100%' },
  assulter_card: { id: 'assulter_card', monsterId: 'assulter', name: '风灵龟卡片', icon: '⚔️', slot: 'weapon', bonus: {"hpPct":20,"str":10}, desc: '普通攻击暴击时，伤害增加10%。, 对人型系魔物，CRI+7, 果树龟、岩石龟、水灵龟、火焰龟卡片一起装备时，物理攻击时可施展自动念咒、无视体型攻击1技能。, HP恢复力增加50%。, 每当击杀敌人时，有一定几率会掉落红色药水。, MaxHP +20%, STR+10, 当套装装备者是剑士系列的角色时，吃下红色药水、黄色药水、白色药水时恢复量增加50%。' },
  aster_card: { id: 'aster_card', monsterId: 'aster', name: '海星卡片', icon: '⚔️', slot: 'weapon', bonus: {"atk":5}, desc: '对贝壳魔灵的伤害，增加30%。, ATK+5' },
  wild_rose_card: { id: 'wild_rose_card', monsterId: 'wild_rose', name: '狂暴野猫卡片', icon: '👢', slot: 'footgear', bonus: {"agi":1,"perfectDodge":5}, desc: 'AGI+1, 完全回避+5' },
  wooden_golem_card: { id: 'wooden_golem_card', monsterId: 'wooden_golem', name: '机木人卡片', icon: '🃏', slot: 'any', bonus: {"def":1}, desc: 'HP恢复力上升30%, DEF+1' },
  wootan_shooter_card: { id: 'wootan_shooter_card', monsterId: 'wootan_shooter', name: '伍坦弹弓手卡片', icon: '🃏', slot: 'any', bonus: {"def":1}, desc: '受到攻击时，被混乱的几率降低20%, DEF+1' },
  wootan_fighter_card: { id: 'wootan_fighter_card', monsterId: 'wootan_fighter', name: '伍坦战士卡片', icon: '🃏', slot: 'any', bonus: {"def":1}, desc: '受到攻击时，被出血的几率降低20%, DEF+1' },
  eclipse_card: { id: 'eclipse_card', monsterId: 'eclipse', name: '蓝疯兔卡片', icon: '🃏', slot: 'any', bonus: {"vit":1}, desc: 'VIT+1, 装备疯兔卡片时，FLEE+18' },
  shellfish_card: { id: 'shellfish_card', monsterId: 'shellfish', name: '贝壳魔灵卡片', icon: '⚔️', slot: 'weapon', bonus: {"atk":5}, desc: '对卡拉蟹的伤害，增加30%, ATK+5' },
  geographer_card: { id: 'geographer_card', monsterId: 'geographer', name: '邪恶向日葵卡片', icon: '🃏', slot: 'any', bonus: {"vit":10}, desc: '受到物理伤害时，当习得自动念咒、天使之赐福2技能、天使之赐福10技能时，可使用10技能天使之赐福。, 飞行魔书、猴桃木、甜饼人、海豹宝宝卡片一起装备时，咏唱时间减少10%。, 技能使用时SP消耗量，减少10%。, VIT+10, 当套装装备者是服事系列角色时，从恶魔系和不死系魔物受到的伤害减少30%，击杀恶魔系和不死系魔物时，所得到的经验值+5%。' },
  choco_card: { id: 'choco_card', monsterId: 'choco', name: '巧克猴卡片', icon: '🃏', slot: 'any', bonus: {"perfectDodge":5}, desc: '完全回避+5' },
  cookie_card: { id: 'cookie_card', monsterId: 'cookie', name: '甜饼人卡片', icon: '🃏', slot: 'any', bonus: {"luk":2}, desc: 'LUK+2, 神圣之光伤害，增加10%' },
  whisper_boss_card: { id: 'whisper_boss_card', monsterId: 'whisper_boss', name: '巨大白幽灵卡片', icon: '🃏', slot: 'any', bonus: {"flee":10}, desc: 'FLEE+10, STR80以上时，ATK+20, VIT80以上时，MAXHP+3%, LUK80以上时，CRI+3' },
  toad_card: { id: 'toad_card', monsterId: 'toad', name: '蛙王卡片', icon: '🃏', slot: 'any', bonus: {"perfectDodge":1}, desc: '完全回避+1, 装备罗达蛙卡片时，FLEE+18' },
  parasite_card: { id: 'parasite_card', monsterId: 'parasite', name: '苗娃佩瑞丝卡片', icon: '🛡️', slot: 'shield', bonus: {"def":1}, desc: 'DEF+1, 受到无属性的伤害减少5%' },
  hylozoist_card: { id: 'hylozoist_card', monsterId: 'hylozoist', name: '兔斯拉卡片', icon: '🃏', slot: 'any', bonus: {"luk":10}, desc: '有一定的几率，让魔物变换成其它的魔物。, 奈吉鸟、拉链熊、邪恶礼盒、小花豹卡片一起装备时、每当攻击时SP恢复2。, 使用金钱攻击技能时，伤害增加20%。, LUK+10, 当套装装备者是商人系列角色时，每当击杀魔物时有一定的几率会掉落神秘紫箱，有20%的几率让魔法反射。' },
  dark_snake_lord_card: { id: 'dark_snake_lord_card', monsterId: 'dark_snake_lord', name: '墨蛇君卡片', icon: '🃏', slot: 'any', bonus: {"int":3}, desc: '不会得到黑暗和诅咒, INT+3' },
  heater_card: { id: 'heater_card', monsterId: 'heater', name: '火焰龟卡片', icon: '🃏', slot: 'any', bonus: {"critRate":3,"perfectDodge":3}, desc: 'CRI+3, 完全回避+3' },
  waste_stove_card: { id: 'waste_stove_card', monsterId: 'waste_stove', name: '废铁暖炉卡片', icon: '🃏', slot: 'any', bonus: {"atk":5,"int":1}, desc: 'ATK+5, INT+1, 当和海豹宝宝，飞行魔书，甜饼人卡片一起装备时，STR+3，SP+80，物理攻击时以较低的几率有自动念咒、天使之光5技能使用，阿修罗霸凰拳增加10%的伤害，ATK+25。, 当武僧装备时，SP消耗量减少10%，施法时间不会被打断' },
  porcellio_card: { id: 'porcellio_card', monsterId: 'porcellio', name: '三叶铁甲虫卡片', icon: '🃏', slot: 'any', bonus: {"atk":25}, desc: 'ATK+25, DEF-5' },
  mineral_card: { id: 'mineral_card', monsterId: 'mineral', name: '矿石魔卡片', icon: '🃏', slot: 'any', bonus: {"def":3}, desc: 'ATK-25, DEF+3' },
  mole_card: { id: 'mole_card', monsterId: 'mole', name: '摩尔卡片', icon: '🃏', slot: 'any', bonus: {"luk":2}, desc: 'LUK+2, 当和拉链熊，小花豹，奈吉鸟，摩卡卡片一起装备时，金钱攻击伤害增加20%，攻击时SP1 恢复，MHP增加7%，MSP增加7%，STR+4, 炼金术师装备时，物理攻击时，有一定几率使用自动念咒、 速度激发 1技能。当抓到魔物时有一定几率会得到护贝药、植物梗' },
  kavac_card: { id: 'kavac_card', monsterId: 'kavac', name: '闇●弓箭手卡片', icon: '🧣', slot: 'garment', bonus: {"flee":10,"perfectDodge":4}, desc: 'FLEE+10, 完全回避+4' },
  breeze_card: { id: 'breeze_card', monsterId: 'breeze', name: '微风卡片', icon: '⚔️', slot: 'weapon', bonus: {"atk":5}, desc: 'ATK+5, 攻击时，有5%的几率得到出血' },
  tha_maero_card: { id: 'tha_maero_card', monsterId: 'tha_maero', name: '达纳托斯的悲哀卡片', icon: '⚔️', slot: 'weapon', bonus: {"atk":5}, desc: 'ATK+5, 物理攻击时，有一定的几率施展自动念咒、缓速术 3级' },
  alicel_card: { id: 'alicel_card', monsterId: 'alicel', name: '爱丽削卡片', icon: '🃏', slot: 'any', bonus: {"flee":10}, desc: 'FLEE+10, DEF-5' },
  hodremlin_card: { id: 'hodremlin_card', monsterId: 'hodremlin', name: '邪恶妖精卡片', icon: '🛡️', slot: 'shield', bonus: {"perfectDodge":10}, desc: '减少从小，中，大型受到的伤害 15%, 完全回避+10' },
  roween_card: { id: 'roween_card', monsterId: 'roween', name: '鼬卡片', icon: '🃏', slot: 'any', bonus: {"perfectDodge":5}, desc: '完全回避+5, 对水属性魔物造成物理伤害加10%，对鱼贝类魔物 CRI+15' },
  p_skeleton_card: { id: 'p_skeleton_card', monsterId: null, name: '强化邪骸战士卡片', icon: '⚔️', slot: 'weapon', bonus: {"atk":15}, desc: 'ATK+15, 攻击时有2%让对方陷入眩晕。, 若装备者的等级为100以上时，眩晕几率增加1%。' },
  duneirre_card: { id: 'duneirre_card', monsterId: 'duneyrr', name: '杜内尔卡片', icon: '👑', slot: 'headgear', bonus: {"atk":10,"perfectDodge":4}, desc: 'ATK+10, 完全回避+4' },
  lata_card: { id: 'lata_card', monsterId: 'rata', name: '拉塔卡片', icon: '👑', slot: 'headgear', bonus: {"matk":10}, desc: 'MATK+10, 魔法攻击时有一定几率4秒内固定咏唱减少50%。' },
  hardrock_mommos_card: { id: 'hardrock_mommos_card', monsterId: 'hardrock_mommoth', name: '硬石猛犸卡片', icon: '🃏', slot: 'any', bonus: {"def":5}, desc: 'DEF+5, 精炼+12以上时DEF+20、MHP+10%。, 精炼+14以上时MHP额外+3%。' },
  sealed_apocalips_h_card: { id: 'sealed_apocalips_h_card', monsterId: null, name: '封印贝思波卡片', icon: '👑', slot: 'headgear', bonus: {"dex":2}, desc: '魔法攻击时，对于Boss系魔物的魔法防御力有15%的无视而对伤害。, 当精炼能力+15以上时，对于Boss系魔物的魔法防御力有25%的无视而对伤害。, DEX+2' },
  leak_card: { id: 'leak_card', monsterId: 'leak', name: '让特卡片', icon: '🃏', slot: 'any', bonus: {"str":3}, desc: 'STR+3, 受到物理、魔法攻击时，有较高的几率对敌人施展混乱、恐怖。' },
  kraken_card: { id: 'kraken_card', monsterId: 'kraken', name: '魔鬼大乌贼卡片', icon: '🃏', slot: 'any', bonus: {"flee":10}, desc: 'FLEE+10, 可使用【隐匿】Lv1、【潜击】Lv1。, 使用【潜击】时有一定几率对敌人施展出血。' },
  wild_rider_card: { id: 'wild_rider_card', monsterId: 'wild_rider', name: '野猫骑士卡片', icon: '🃏', slot: 'any', bonus: {"agi":1}, desc: 'AGI+1, 物理攻击时较高的几率对自身施展加速术Lv1。' },
  giant_octopus_card: { id: 'giant_octopus_card', monsterId: null, name: '狂暴章鱼卡片', icon: '🃏', slot: 'any', bonus: {"hpPct":12}, desc: 'MaxHP +12%, 可使用【水球术】Lv5。' },
  fenrir_card: { id: 'fenrir_card', monsterId: null, name: '弱化的潘利尔卡片', icon: '👑', slot: 'headgear', bonus: {"matk":25}, desc: 'MATK+25' },
  alphoccio_card: { id: 'alphoccio_card', monsterId: 'alphoccio', name: '闇●搞笑艺人卡片', icon: '🃏', slot: 'any', bonus: {"flee":10}, desc: 'FLEE+10, 诗人系列装备时MHP+10%、MSP+5%' },
  ceila_card: { id: 'ceila_card', monsterId: 'celia', name: '闇●智者卡片', icon: '🃏', slot: 'any', bonus: {"flee":10}, desc: 'FLEE+10, 可使用随机技能Lv1。' },
  chen_card: { id: 'chen_card', monsterId: 'chen', name: '闇●武术宗师卡片', icon: '🃏', slot: 'any', bonus: {"flee":10}, desc: 'FLEE+10, 可使用蓄气Lv2。' },
  flamel_card: { id: 'flamel_card', monsterId: 'flamel', name: '闇●创造者卡片', icon: '🃏', slot: 'any', bonus: {"flee":10}, desc: 'FLEE+10, 红色、黄色、白色纤细药水的恢复力增加200%。' },
  gertie_card: { id: 'gertie_card', monsterId: 'gertie', name: '闇●神行太保卡片', icon: '🃏', slot: 'any', bonus: {"flee":10}, desc: 'FLEE+10, 可使用紧密的约束Lv1。' },
  randel_card: { id: 'randel_card', monsterId: 'randel', name: '闇●圣殿十字军卡片', icon: '🃏', slot: 'any', bonus: {"flee":10}, desc: 'FLEE+10, 可使用自动防御Lv3。' },
  trentini_card: { id: 'trentini_card', monsterId: 'trentini', name: '闇●冷艳舞姬卡片', icon: '🃏', slot: 'any', bonus: {"flee":10}, desc: 'FLEE+10, 舞娘系列装备时MHP+10%、MSP+5%。' },
  soheon_card: { id: 'soheon_card', monsterId: null, name: '卫士小贤卡片', icon: '⚔️', slot: 'weapon', bonus: {"atk":10}, desc: 'ATK+10, 武器为短剑，精炼+10以上时ASPD+1，精炼+14以上时ASPD额外提高 1。' },
  corruption_root_card: { id: 'corruption_root_card', monsterId: null, name: '堕落根茎卡片', icon: '⚔️', slot: 'weapon', bonus: {"atk":20}, desc: 'ATK+20, 近距离物理攻击时，有很高的几率在施展者周围5*5范围内，对所有敌人施予石化、催眠、诅咒。' },
  watcher_card: { id: 'watcher_card', monsterId: 'watcher', name: '观察者卡片', icon: '🃏', slot: 'any', bonus: {"atk":30}, desc: 'ATK+30, 每当被敌人攻击时SP-5。' },
  ifn_toad_card: { id: 'ifn_toad_card', monsterId: null, name: '无限蛙王卡片', icon: '🃏', slot: 'any', bonus: {"perfectDodge":18}, desc: '完全回避+2, 完全回避+7, 完全回避+9' },
  eggring_card: { id: 'eggring_card', monsterId: 'dr_eggring', name: '蛋黄波利卡片', icon: '🃏', slot: 'any', bonus: {"luk":2,"hp":50}, desc: 'LUK+2, MaxHP +50' },
  leaf_lunatic_card: { id: 'leaf_lunatic_card', monsterId: 'dr_lunatic', name: '群叶疯兔卡片', icon: '👢', slot: 'footgear', bonus: {"sp":5}, desc: 'MaxSP +5' },
  grass_fabre_card: { id: 'grass_fabre_card', monsterId: 'dr_fabre', name: '草地绿棉虫卡片', icon: '🃏', slot: 'any', bonus: {"luk":1,"hp":100}, desc: 'LUK+1, MaxHP +100' },
  wild_honet_card: { id: 'wild_honet_card', monsterId: 'dr_hornet', name: '狂野蜂兵卡片', icon: '⚔️', slot: 'weapon', bonus: {"atk":5}, desc: 'ATK+5' },
  sw_roda_frog_card: { id: 'sw_roda_frog_card', monsterId: 'dr_roda_frog', name: '甜心罗达蛙卡片', icon: '🃏', slot: 'any', bonus: {"sp":10,"hp":300}, desc: 'MaxSP +10, MaxHP +300' },
  hunter_wolf_card: { id: 'hunter_wolf_card', monsterId: 'dr_desert_wolf_b', name: '狩猎沙漠之狼卡片', icon: '👢', slot: 'footgear', bonus: {"sp":30}, desc: 'MaxSP +30' },
  trance_spore_card: { id: 'trance_spore_card', monsterId: 'dr_spore', name: '变形魔菇卡片', icon: '👑', slot: 'headgear', bonus: {"vit":1,"int":1}, desc: 'VIT+1, INT+1' },
  guillotine_cross_card: { id: 'guillotine_cross_card', monsterId: null, name: '闇·十字切割者 艾勒梅斯卡片', icon: '🃏', slot: 'any', bonus: {"perfectDodge":10}, desc: '完全回避+10, BaseLv为175时，, All State+10。, 披风精炼值+10时，, All State+10。, 与真·十字切割者一起装备时，物理攻击时有3%的几率变身为闇·十字刺客6秒。, 变身期间，ATK+100。' },
  strength1: { id: 'strength1', monsterId: null, name: 'STR+1', icon: '🃏', slot: 'any', bonus: {"str":1}, desc: 'STR+1, ^ffffff_^000000' },
  strength2: { id: 'strength2', monsterId: null, name: 'STR+2', icon: '🃏', slot: 'any', bonus: {"str":2}, desc: 'STR+2, ^ffffff_^000000' },
  strength3: { id: 'strength3', monsterId: null, name: 'STR+3', icon: '🃏', slot: 'any', bonus: {"str":3}, desc: 'STR+3, ^ffffff_^000000' },
  strength4: { id: 'strength4', monsterId: null, name: 'STR+4', icon: '🃏', slot: 'any', bonus: {"str":4}, desc: 'STR+4, ^ffffff_^000000' },
  strength5: { id: 'strength5', monsterId: null, name: 'STR+5', icon: '🃏', slot: 'any', bonus: {"str":5}, desc: 'STR+5, ^ffffff_^000000' },
  strength6: { id: 'strength6', monsterId: null, name: 'STR+6', icon: '🃏', slot: 'any', bonus: {"str":6}, desc: 'STR+6, ^ffffff_^000000' },
  strength7: { id: 'strength7', monsterId: null, name: 'STR+7', icon: '🃏', slot: 'any', bonus: {"str":7}, desc: 'STR+7, ^ffffff_^000000' },
  strength8: { id: 'strength8', monsterId: null, name: 'STR+8', icon: '🃏', slot: 'any', bonus: {"str":8}, desc: 'STR+8, ^ffffff_^000000' },
  strength9: { id: 'strength9', monsterId: null, name: 'STR+9', icon: '🃏', slot: 'any', bonus: {"str":9}, desc: 'STR+9, ^ffffff_^000000' },
  strength10: { id: 'strength10', monsterId: null, name: 'STR+10', icon: '🃏', slot: 'any', bonus: {"str":10}, desc: 'STR+10, ^ffffff_^000000' },
  inteligence1: { id: 'inteligence1', monsterId: null, name: 'INT+1', icon: '🃏', slot: 'any', bonus: {"int":1}, desc: 'INT+1, ^ffffff_^000000' },
  inteligence2: { id: 'inteligence2', monsterId: null, name: 'INT+2', icon: '🃏', slot: 'any', bonus: {"int":2}, desc: 'INT+2, ^ffffff_^000000' },
  inteligence3: { id: 'inteligence3', monsterId: null, name: 'INT+3', icon: '🃏', slot: 'any', bonus: {"int":3}, desc: 'INT+3, ^ffffff_^000000' },
  inteligence4: { id: 'inteligence4', monsterId: null, name: 'INT+4', icon: '🃏', slot: 'any', bonus: {"int":4}, desc: 'INT+4, ^ffffff_^000000' },
  inteligence5: { id: 'inteligence5', monsterId: null, name: 'INT+5', icon: '🃏', slot: 'any', bonus: {"int":5}, desc: 'INT+5, ^ffffff_^000000' },
  inteligence6: { id: 'inteligence6', monsterId: null, name: 'INT+6', icon: '🃏', slot: 'any', bonus: {"int":6}, desc: 'INT+6, ^ffffff_^000000' },
  inteligence7: { id: 'inteligence7', monsterId: null, name: 'INT+7', icon: '🃏', slot: 'any', bonus: {"int":7}, desc: 'INT+7, ^ffffff_^000000' },
  inteligence8: { id: 'inteligence8', monsterId: null, name: 'INT+8', icon: '🃏', slot: 'any', bonus: {"int":8}, desc: 'INT+8, ^ffffff_^000000' },
  inteligence9: { id: 'inteligence9', monsterId: null, name: 'INT+9', icon: '🃏', slot: 'any', bonus: {"int":9}, desc: 'INT+9, ^ffffff_^000000' },
  inteligence10: { id: 'inteligence10', monsterId: null, name: 'INT+10', icon: '🃏', slot: 'any', bonus: {"int":10}, desc: 'INT+10, ^ffffff_^000000' },
  dexterity1: { id: 'dexterity1', monsterId: null, name: 'DEX+1', icon: '🃏', slot: 'any', bonus: {"dex":1}, desc: 'DEX+1, ^ffffff_^000000' },
  dexterity2: { id: 'dexterity2', monsterId: null, name: 'DEX+2', icon: '🃏', slot: 'any', bonus: {"dex":2}, desc: 'DEX+2, ^ffffff_^000000' },
  dexterity3: { id: 'dexterity3', monsterId: null, name: 'DEX+3', icon: '🃏', slot: 'any', bonus: {"dex":3}, desc: 'DEX+3, ^ffffff_^000000' },
  dexterity4: { id: 'dexterity4', monsterId: null, name: 'DEX+4', icon: '🃏', slot: 'any', bonus: {"dex":4}, desc: 'DEX+4, ^ffffff_^000000' },
  dexterity5: { id: 'dexterity5', monsterId: null, name: 'DEX+5', icon: '🃏', slot: 'any', bonus: {"dex":5}, desc: 'DEX+5, ^ffffff_^000000' },
  dexterity6: { id: 'dexterity6', monsterId: null, name: 'DEX+6', icon: '🃏', slot: 'any', bonus: {"dex":6}, desc: 'DEX+6, ^ffffff_^000000' },
  dexterity7: { id: 'dexterity7', monsterId: null, name: 'DEX+7', icon: '🃏', slot: 'any', bonus: {"dex":7}, desc: 'DEX+7, ^ffffff_^000000' },
  dexterity8: { id: 'dexterity8', monsterId: null, name: 'DEX+8', icon: '🃏', slot: 'any', bonus: {"dex":8}, desc: 'DEX+8, ^ffffff_^000000' },
  dexterity9: { id: 'dexterity9', monsterId: null, name: 'DEX+9', icon: '🃏', slot: 'any', bonus: {"dex":9}, desc: 'DEX+9, ^ffffff_^000000' },
  dexterity10: { id: 'dexterity10', monsterId: null, name: 'DEX+10', icon: '🃏', slot: 'any', bonus: {"dex":10}, desc: 'DEX+10, ^ffffff_^000000' },
  agility1: { id: 'agility1', monsterId: null, name: 'AGI+1', icon: '🃏', slot: 'any', bonus: {"agi":1}, desc: 'AGI+1, ^ffffff_^000000' },
  agility2: { id: 'agility2', monsterId: null, name: 'AGI+2', icon: '🃏', slot: 'any', bonus: {"agi":2}, desc: 'AGI+2, ^ffffff_^000000' },
  agility3: { id: 'agility3', monsterId: null, name: 'AGI+3', icon: '🃏', slot: 'any', bonus: {"agi":3}, desc: 'AGI+3, ^ffffff_^000000' },
  agility4: { id: 'agility4', monsterId: null, name: 'AGI+4', icon: '🃏', slot: 'any', bonus: {"agi":4}, desc: 'AGI+4, ^ffffff_^000000' },
  agility7: { id: 'agility7', monsterId: null, name: 'AGI+7', icon: '🃏', slot: 'any', bonus: {"agi":7}, desc: 'AGI+7, ^ffffff_^000000' },
  agility8: { id: 'agility8', monsterId: null, name: 'AGI+8', icon: '🃏', slot: 'any', bonus: {"agi":8}, desc: 'AGI+8, ^ffffff_^000000' },
  agility9: { id: 'agility9', monsterId: null, name: 'AGI+9', icon: '🃏', slot: 'any', bonus: {"agi":9}, desc: 'AGI+9, ^ffffff_^000000' },
  agility10: { id: 'agility10', monsterId: null, name: 'AGI+10', icon: '🃏', slot: 'any', bonus: {"agi":10}, desc: 'AGI+10, ^ffffff_^000000' },
  vitality1: { id: 'vitality1', monsterId: null, name: 'VIT+1', icon: '🃏', slot: 'any', bonus: {"vit":1}, desc: 'VIT+1, ^ffffff_^000000' },
  vitality2: { id: 'vitality2', monsterId: null, name: 'VIT+2', icon: '🃏', slot: 'any', bonus: {"vit":2}, desc: 'VIT+2, ^ffffff_^000000' },
  vitality3: { id: 'vitality3', monsterId: null, name: 'VIT+3', icon: '🃏', slot: 'any', bonus: {"vit":3}, desc: 'VIT+3, ^ffffff_^000000' },
  vitality4: { id: 'vitality4', monsterId: null, name: 'VIT+4', icon: '🃏', slot: 'any', bonus: {"vit":4}, desc: 'VIT+4, ^ffffff_^000000' },
  vitality5: { id: 'vitality5', monsterId: null, name: 'VIT+5', icon: '🃏', slot: 'any', bonus: {"vit":5}, desc: 'VIT+5, ^ffffff_^000000' },
  vitality6: { id: 'vitality6', monsterId: null, name: 'VIT+6', icon: '🃏', slot: 'any', bonus: {"vit":6}, desc: 'VIT+6, ^ffffff_^000000' },
  vitality7: { id: 'vitality7', monsterId: null, name: 'VIT+7', icon: '🃏', slot: 'any', bonus: {"vit":7}, desc: 'VIT+7, ^ffffff_^000000' },
  vitality8: { id: 'vitality8', monsterId: null, name: 'VIT+8', icon: '🃏', slot: 'any', bonus: {"vit":8}, desc: 'VIT+8, ^ffffff_^000000' },
  vitality9: { id: 'vitality9', monsterId: null, name: 'VIT+9', icon: '🃏', slot: 'any', bonus: {"vit":9}, desc: 'VIT+9, ^ffffff_^000000' },
  vitality10: { id: 'vitality10', monsterId: null, name: 'VIT+10', icon: '🃏', slot: 'any', bonus: {"vit":10}, desc: 'VIT+10, ^ffffff_^000000' },
  luck1: { id: 'luck1', monsterId: null, name: 'LUK+1', icon: '🃏', slot: 'any', bonus: {"luk":1}, desc: 'LUK+1, ^ffffff_^000000' },
  luck2: { id: 'luck2', monsterId: null, name: 'LUK+2', icon: '🃏', slot: 'any', bonus: {"luk":2}, desc: 'LUK+2, ^ffffff_^000000' },
  luck3: { id: 'luck3', monsterId: null, name: 'LUK+3', icon: '🃏', slot: 'any', bonus: {"luk":3}, desc: 'LUK+3, ^ffffff_^000000' },
  luck4: { id: 'luck4', monsterId: null, name: 'LUK+4', icon: '🃏', slot: 'any', bonus: {"luk":4}, desc: 'LUK+4, ^ffffff_^000000' },
  luck5: { id: 'luck5', monsterId: null, name: 'LUK+5', icon: '🃏', slot: 'any', bonus: {"luk":5}, desc: 'LUK+5, ^ffffff_^000000' },
  luck6: { id: 'luck6', monsterId: null, name: 'LUK+6', icon: '🃏', slot: 'any', bonus: {"luk":6}, desc: 'LUK+6, ^ffffff_^000000' },
  luck7: { id: 'luck7', monsterId: null, name: 'LUK+7', icon: '🃏', slot: 'any', bonus: {"luk":7}, desc: 'LUK+7, ^ffffff_^000000' },
  luck8: { id: 'luck8', monsterId: null, name: 'LUK+8', icon: '🃏', slot: 'any', bonus: {"luk":8}, desc: 'LUK+8, ^ffffff_^000000' },
  luck9: { id: 'luck9', monsterId: null, name: 'LUK+9', icon: '🃏', slot: 'any', bonus: {"luk":9}, desc: 'LUK+9, ^ffffff_^000000' },
  luck10: { id: 'luck10', monsterId: null, name: 'LUK+10', icon: '🃏', slot: 'any', bonus: {"luk":10}, desc: 'LUK+10, ^ffffff_^000000' },
  str1_j: { id: 'str1_j', monsterId: null, name: 'STR+1', icon: '🃏', slot: 'any', bonus: {"str":1}, desc: 'STR+1' },
  int1_j: { id: 'int1_j', monsterId: null, name: 'INT+1', icon: '🃏', slot: 'any', bonus: {"int":1}, desc: 'INT+1' },
  vit1_j: { id: 'vit1_j', monsterId: null, name: 'VIT+1', icon: '🃏', slot: 'any', bonus: {"vit":1}, desc: 'VIT+1' },
  agi1_j: { id: 'agi1_j', monsterId: null, name: 'AGI+1', icon: '🃏', slot: 'any', bonus: {"agi":1}, desc: 'AGI+1' },
  dex1_j: { id: 'dex1_j', monsterId: null, name: 'DEX+1', icon: '🃏', slot: 'any', bonus: {"dex":1}, desc: 'DEX+1' },
  luk1_j: { id: 'luk1_j', monsterId: null, name: 'LUK+1', icon: '🃏', slot: 'any', bonus: {"luk":1}, desc: 'LUK+1' },
  def3: { id: 'def3', monsterId: null, name: 'DEF+3', icon: '🃏', slot: 'any', bonus: {"def":3}, desc: 'DEF+3' },
  def6: { id: 'def6', monsterId: null, name: 'DEF+6', icon: '🃏', slot: 'any', bonus: {"def":6}, desc: 'DEF+6' },
  def9: { id: 'def9', monsterId: null, name: 'DEF+9', icon: '🃏', slot: 'any', bonus: {"def":9}, desc: 'DEF+9' },
  def12: { id: 'def12', monsterId: null, name: 'DEF+12', icon: '🃏', slot: 'any', bonus: {"def":12}, desc: 'DEF+12' },
  hit1: { id: 'hit1', monsterId: null, name: 'HIT+1', icon: '🃏', slot: 'any', bonus: {"hit":1}, desc: 'HIT+1' },
  def15: { id: 'def15', monsterId: null, name: 'DEF+15', icon: '🃏', slot: 'any', bonus: {"def":15}, desc: 'DEF+15' },
  def18: { id: 'def18', monsterId: null, name: 'DEF+18', icon: '🃏', slot: 'any', bonus: {"def":18}, desc: 'DEF+18' },
  def21: { id: 'def21', monsterId: null, name: 'DEF+21', icon: '🃏', slot: 'any', bonus: {"def":21}, desc: 'DEF+21' },
  force1: { id: 'force1', monsterId: null, name: '魔神的武力精髓1', icon: '🃏', slot: 'any', bonus: {"str":1,"atk":3}, desc: '魔神梦罗克精髓中的一种，内含魔神的部分能力。, STR+1, ATK+3, INT-1, ^ff0000注意 : 此为特殊附魔物品，因此不在卡片保护、卡片分解的范围内。^000000, 装备: ^777777所有字段皆可^000000, 重量: ^7777771^000000' },
  force2: { id: 'force2', monsterId: null, name: '魔神的武力精髓2', icon: '🃏', slot: 'any', bonus: {"str":2,"atk":6}, desc: '魔神梦罗克精髓中的一种，内含魔神的部分能力。, STR+2, ATK+6, INT-2, ^ff0000注意 : 此为特殊附魔物品，因此不在卡片保护、卡片分解的范围内。^000000, 装备: ^777777所有字段皆可^000000, 重量: ^7777771^000000' },
  force3: { id: 'force3', monsterId: null, name: '魔神的武力精髓3', icon: '🃏', slot: 'any', bonus: {"str":4,"atk":12}, desc: '魔神梦罗克精髓中的一种，内含魔神的部分能力。, STR+4, ATK+12, INT-4, ^ff0000注意 : 此为特殊附魔物品，因此不在卡片保护、卡片分解的范围内。^000000, 装备: ^777777所有字段皆可^000000, 重量: ^7777771^000000' },
  intellect1: { id: 'intellect1', monsterId: null, name: '魔神的智慧精髓1', icon: '🃏', slot: 'any', bonus: {"int":1,"matk":3}, desc: '魔神梦罗克精髓中的一种，内含魔神的部分能力。, INT+1, MATK+3, STR-1, ^ff0000注意 : 此为特殊附魔物品，因此不在卡片保护、卡片分解的范围内。^000000, 装备: ^777777所有字段皆可^000000, 重量: ^7777771^000000' },
  intellect2: { id: 'intellect2', monsterId: null, name: '魔神的智慧精髓2', icon: '🃏', slot: 'any', bonus: {"int":2,"matk":6}, desc: '魔神梦罗克精髓中的一种，内含魔神的部分能力。, INT+2, MATK+6, STR-2, ^ff0000注意 : 此为特殊附魔物品，因此不在卡片保护、卡片分解的范围内。^000000, 装备: ^777777所有字段皆可^000000, 重量: ^7777771^000000' },
  intellect3: { id: 'intellect3', monsterId: null, name: '魔神的智慧精髓3', icon: '🃏', slot: 'any', bonus: {"int":4,"matk":12}, desc: '魔神梦罗克精髓中的一种，内含魔神的部分能力。, INT+4, MATK+12, STR-4, ^ff0000注意 : 此为特殊附魔物品，因此不在卡片保护、卡片分解的范围内。^000000, 装备: ^777777所有字段皆可^000000, 重量: ^7777771^000000' },
  swiftness1: { id: 'swiftness1', monsterId: null, name: '魔神的速度精髓1', icon: '🃏', slot: 'any', bonus: {"agi":1,"flee":2}, desc: '魔神梦罗克精髓中的一种，内含魔神的部分能力。, AGI+1, FLEE+2, VIT-1, ^ff0000注意 : 此为特殊附魔物品，因此不在卡片保护、卡片分解的范围内。^000000, 装备: ^777777所有字段皆可^000000, 重量: ^7777771^000000' },
  swiftness2: { id: 'swiftness2', monsterId: null, name: '魔神的速度精髓2', icon: '🃏', slot: 'any', bonus: {"agi":2,"flee":4}, desc: '魔神梦罗克精髓中的一种，内含魔神的部分能力。, AGI+2, FLEE+4, VIT-2, ^ff0000注意 : 此为特殊附魔物品，因此不在卡片保护、卡片分解的范围内。^000000, 装备: ^777777所有字段皆可^000000, 重量: ^7777771^000000' },
  swiftness3: { id: 'swiftness3', monsterId: null, name: '魔神的速度精髓3', icon: '🃏', slot: 'any', bonus: {"agi":4,"flee":8}, desc: '魔神梦罗克精髓中的一种，内含魔神的部分能力。, AGI+4, FLEE+8, VIT-4, ^ff0000注意 : 此为特殊附魔物品，因此不在卡片保护、卡片分解的范围内。^000000, 装备: ^777777所有字段皆可^000000, 重量: ^7777771^000000' },
  tough1: { id: 'tough1', monsterId: null, name: '魔神的体力精髓1', icon: '🃏', slot: 'any', bonus: {"vit":1,"def":3}, desc: '魔神梦罗克精髓中的一种，内含魔神的部分能力。, VIT+1, DEF+3, MDEF+2, AGI-1, ^ff0000注意 : 此为特殊附魔物品，因此不在卡片保护、卡片分解的范围内。^000000, 装备: ^777777所有字段皆可^000000, 重量: ^7777771^000000' },
  tough2: { id: 'tough2', monsterId: null, name: '魔神的体力精髓2', icon: '🃏', slot: 'any', bonus: {"vit":2,"def":6}, desc: '魔神梦罗克精髓中的一种，内含魔神的部分能力。, VIT+2, DEF+6, MDEF+4, AGI-2, ^ff0000注意 : 此为特殊附魔物品，因此不在卡片保护、卡片分解的范围内。^000000, 装备: ^777777所有字段皆可^000000, 重量: ^7777771^000000' },
  tough3: { id: 'tough3', monsterId: null, name: '魔神的体力精髓3', icon: '🃏', slot: 'any', bonus: {"vit":4,"def":12}, desc: '魔神梦罗克精髓中的一种，内含魔神的部分能力。, VIT+4, DEF+12, MDEF+8, AGI-4, ^ff0000注意 : 此为特殊附魔物品，因此不在卡片保护、卡片分解的范围内。^000000, 装备: ^777777所有字段皆可^000000, 重量: ^7777771^000000' },
  artful1: { id: 'artful1', monsterId: null, name: '魔神的集中精髓1', icon: '🃏', slot: 'any', bonus: {"dex":1,"hit":2}, desc: '魔神梦罗克精髓中的一种，内含魔神的部分能力。, DEX+1, HIT+2, LUK-1, ^ff0000注意 : 此为特殊附魔物品，因此不在卡片保护、卡片分解的范围内。^000000, 装备: ^777777所有字段皆可^000000, 重量: ^7777771^000000' },
  artful2: { id: 'artful2', monsterId: null, name: '魔神的集中精髓2', icon: '🃏', slot: 'any', bonus: {"dex":2,"hit":4}, desc: '魔神梦罗克精髓中的一种，内含魔神的部分能力。, DEX+2, HIT+4, LUK-2, ^ff0000注意 : 此为特殊附魔物品，因此不在卡片保护、卡片分解的范围内。^000000, 装备: ^777777所有字段皆可^000000, 重量: ^7777771^000000' },
  artful3: { id: 'artful3', monsterId: null, name: '魔神的集中精髓3', icon: '🃏', slot: 'any', bonus: {"dex":4,"hit":8}, desc: '魔神梦罗克精髓中的一种，内含魔神的部分能力。, DEX+4, HIT+8, LUK-4, ^ff0000注意 : 此为特殊附魔物品，因此不在卡片保护、卡片分解的范围内。^000000, 装备: ^777777所有字段皆可^000000, 重量: ^7777771^000000' },
  fortune1: { id: 'fortune1', monsterId: null, name: '魔神的幸运精髓1', icon: '🃏', slot: 'any', bonus: {"luk":1,"critRate":1}, desc: '魔神梦罗克精髓中的一种，内含魔神的部分能力。, LUK+1, CRI+1, DEX-1, ^ff0000注意 : 此为特殊附魔物品，因此不在卡片保护、卡片分解的范围内。^000000, 装备: ^777777所有字段皆可^000000, 重量: ^7777771^000000' },
  fortune2: { id: 'fortune2', monsterId: null, name: '魔神的幸运精髓2', icon: '🃏', slot: 'any', bonus: {"luk":2,"critRate":2}, desc: '魔神梦罗克精髓中的一种，内含魔神的部分能力。, LUK+2, CRI+2, DEX-2, ^ff0000注意 : 此为特殊附魔物品，因此不在卡片保护、卡片分解的范围内。^000000, 装备: ^777777所有字段皆可^000000, 重量: ^7777771^000000' },
  fortune3: { id: 'fortune3', monsterId: null, name: '魔神的幸运精髓3', icon: '🃏', slot: 'any', bonus: {"luk":4,"critRate":4}, desc: '魔神梦罗克精髓中的一种，内含魔神的部分能力。, LUK+4, CRI+4, DEX-4, ^ff0000注意 : 此为特殊附魔物品，因此不在卡片保护、卡片分解的范围内。^000000, 装备: ^777777所有字段皆可^000000, 重量: ^7777771^000000' },
  critical1: { id: 'critical1', monsterId: null, name: '暴击Lv1', icon: '🃏', slot: 'any', bonus: {"critRate":1}, desc: 'CRI+1' },
  sp10: { id: 'sp10', monsterId: null, name: 'SP+10', icon: '🃏', slot: 'any', bonus: {"sp":10}, desc: 'MaxSP +10' },
  msp1: { id: 'msp1', monsterId: null, name: 'MSP+1%', icon: '🃏', slot: 'any', bonus: {"spPct":1}, desc: 'MaxSP +1%' },
  critical2: { id: 'critical2', monsterId: null, name: '暴击Lv2', icon: '🃏', slot: 'any', bonus: {"critRate":2}, desc: 'CRI+2' },
  critical3: { id: 'critical3', monsterId: null, name: '暴击Lv3', icon: '🃏', slot: 'any', bonus: {"critRate":4}, desc: 'CRI+4' },
  critical4: { id: 'critical4', monsterId: null, name: '暴击Lv4', icon: '🃏', slot: 'any', bonus: {"critRate":6}, desc: 'CRI+6' },
  dodge1: { id: 'dodge1', monsterId: null, name: '流溢Lv1', icon: '🃏', slot: 'any', bonus: {"perfectDodge":3}, desc: '完全回避+3' },
  dodge2: { id: 'dodge2', monsterId: null, name: '流溢Lv2', icon: '🃏', slot: 'any', bonus: {"perfectDodge":4}, desc: '完全回避+4' },
  dodge3: { id: 'dodge3', monsterId: null, name: '流溢Lv3', icon: '🃏', slot: 'any', bonus: {"perfectDodge":5}, desc: '完全回避+5' },
  reactor_a_avoi: { id: 'reactor_a_avoi', monsterId: null, name: '辅助附魔 完全回避', icon: '🃏', slot: 'any', bonus: {"perfectDodge":3}, desc: '完全回避+3' },
  neev_agi_1: { id: 'neev_agi_1', monsterId: null, name: '敏捷之石Lv1', icon: '🃏', slot: 'any', bonus: {"perfectDodge":10}, desc: '精炼+7时，AGI+5。, 完全回避+10' },
  neev_agi_2: { id: 'neev_agi_2', monsterId: null, name: '敏捷之石Lv2', icon: '🃏', slot: 'any', bonus: {"perfectDodge":11}, desc: '精炼+7时，AGI+6。, 完全回避+11' },
  neev_agi_3: { id: 'neev_agi_3', monsterId: null, name: '敏捷之石Lv3', icon: '🃏', slot: 'any', bonus: {"perfectDodge":25}, desc: '精炼+7时，AGI+7。, 完全回避+12, 完全回避+13' },
  anger_moonlight_card: { id: 'anger_moonlight_card', monsterId: null, name: '愤怒月夜猫卡片', icon: '🃏', slot: 'any', bonus: {"perfectDodge":5}, desc: '可使用神之威压Lv4。, 完全回避+5' },
  matt_drainliar_card: { id: 'matt_drainliar_card', monsterId: 'ill_drainliar', name: '幻影红蝙蝠卡片', icon: '👑', slot: 'headgear', bonus: {"perfectDodge":5}, desc: '绝不会着火。, 完全回避+5' },
  def20: { id: 'def20', monsterId: null, name: 'DEF+20', icon: '🃏', slot: 'any', bonus: {"def":20}, desc: 'DEF+20' },
  dodge1_j: { id: 'dodge1_j', monsterId: null, name: '完全回避+1', icon: '🃏', slot: 'any', bonus: {"perfectDodge":1}, desc: '完全回避+1' },
  dodge2_j: { id: 'dodge2_j', monsterId: null, name: '完全回避+2', icon: '🃏', slot: 'any', bonus: {"perfectDodge":2}, desc: '完全回避+2' },
  atk5: { id: 'atk5', monsterId: null, name: 'ATK+5', icon: '🃏', slot: 'any', bonus: {"atk":5}, desc: 'ATK+5' },
  matk5: { id: 'matk5', monsterId: null, name: 'MATK+5', icon: '🃏', slot: 'any', bonus: {"matk":5}, desc: 'MATK+5' }
};

const MONSTER_CARD_DROPS = {
  poring: { card: 'poring_card', chance: 0.005 },
  fabre: { card: 'fabre_card', chance: 0.005 },
  pupa: { card: 'pupa_card', chance: 0.005 },
  drops: { card: 'drops_card', chance: 0.005 },
  lunatic: { card: 'lunatic_card', chance: 0.005 },
  picky: { card: 'picky_card', chance: 0.005 },
  chonchon: { card: 'chonchon_card', chance: 0.005 },
  wilow: { card: 'wilow_card', chance: 0.005 },
  picky_: { card: 'picky_card', chance: 0.005 },
  thief_bug_egg: { card: 'thief_bug_egg_card', chance: 0.005 },
  ant_egg: { card: 'andre_egg_card', chance: 0.005 },
  roda_frog: { card: 'roda_frog_card', chance: 0.005 },
  condor: { card: 'condor_card', chance: 0.005 },
  thief_bug: { card: 'thief_bug_card', chance: 0.005 },
  hornet: { card: 'hornet_card', chance: 0.005 },
  farmiliar: { card: 'farmiliar_card', chance: 0.005 },
  rocker: { card: 'rocker_card', chance: 0.005 },
  spore: { card: 'spore_card', chance: 0.005 },
  desert_wolf_b: { card: 'desert_wolf_babe_card', chance: 0.005 },
  plankton: { card: 'plankton_card', chance: 0.005 },
  skeleton: { card: 'skeleton_card', chance: 0.005 },
  kukre: { card: 'kukre_card', chance: 0.005 },
  tarou: { card: 'tarou_card', chance: 0.005 },
  wolf: { card: 'wolf_card', chance: 0.005 },
  mandragora: { card: 'mandragora_card', chance: 0.005 },
  ambernite: { card: 'ambernite_card', chance: 0.005 },
  worm_tail: { card: 'worm_tail_card', chance: 0.005 },
  snake: { card: 'snake_card', chance: 0.005 },
  stainer: { card: 'stainer_card', chance: 0.005 },
  coco: { card: 'coco_card', chance: 0.005 },
  steel_chonchon: { card: 'steel_chonchon_card', chance: 0.005 },
  andre: { card: 'andre_card', chance: 0.005 },
  martin: { card: 'martin_card', chance: 0.005 },
  vadon: { card: 'vadon_card', chance: 0.005 },
  thief_bug_: { card: 'thief_bug_male_card', chance: 0.005 },
  yoyo: { card: 'yoyo_card', chance: 0.005 },
  elder_wilow: { card: 'elder_wilow_card', chance: 0.005 },
  marina: { card: 'marina_card', chance: 0.005 },
  dustiness: { card: 'dustiness_card', chance: 0.005 },
  metaller: { card: 'metaller_card', chance: 0.005 },
  cornutus: { card: 'cornutus_card', chance: 0.005 },
  anacondaq: { card: 'anacondaq_card', chance: 0.005 },
  zerom: { card: 'zerom_card', chance: 0.005 },
  kaho: { card: 'kaho_card', chance: 0.005 },
  megalodon: { card: 'megalodon_card', chance: 0.005 },
  drainliar: { card: 'drainliar_card', chance: 0.005 },
  orc_zombie: { card: 'orc_zombie_card', chance: 0.005 },
  golem: { card: 'golem_card', chance: 0.005 },
  argos: { card: 'argos_card', chance: 0.005 },
  magnolia: { card: 'magnolia_card', chance: 0.005 },
  savage: { card: 'savage_card', chance: 0.005 },
  mantis: { card: 'mantis_card', chance: 0.005 },
  hode: { card: 'hode_card', chance: 0.005 },
  desert_wolf: { card: 'desert_wolf_card', chance: 0.005 },
  orc_skeleton: { card: 'orc_skeleton_card', chance: 0.005 },
  soldier_skeleton: { card: 'soldier_skeleton_card', chance: 0.005 },
  sword_fish: { card: 'sword_fish_card', chance: 0.005 },
  munak: { card: 'munak_card', chance: 0.005 },
  kobold_1: { card: 'kobold_card', chance: 0.005 },
  skel_worker: { card: 'skel_worker_card', chance: 0.005 },
  zenorc: { card: 'zenorc_card', chance: 0.005 },
  matyr: { card: 'matyr_card', chance: 0.005 },
  dokebi: { card: 'dokebi_card', chance: 0.005 },
  pasana: { card: 'pasana_card', chance: 0.005 },
  sohee: { card: 'sohee_card', chance: 0.005 },
  sand_man: { card: 'sand_man_card', chance: 0.005 },
  whisper: { card: 'whisper_card', chance: 0.005 },
  mummy: { card: 'mummy_card', chance: 0.005 },
  myst: { card: 'myst_card', chance: 0.005 },
  jakk: { card: 'jakk_card', chance: 0.005 },
  marionette: { card: 'marionette_card', chance: 0.005 },
  argiope: { card: 'argiope_card', chance: 0.005 },
  isis: { card: 'isis_card', chance: 0.005 },
  phreeoni: { card: 'phreeoni_card', chance: 0.005 },
  deviruchi: { card: 'deviruchi_card', chance: 0.005 },
  minorous: { card: 'minorous_card', chance: 0.005 },
  baphomet_: { card: 'baphomet_card', chance: 0.005 },
  evil_druid: { card: 'evil_druid_card', chance: 0.005 },
  ork_hero: { card: 'orc_hero_card', chance: 0.005 },
  crab: { card: 'crab_card', chance: 0.005 },
  nine_tail: { card: 'nine_tail_card', chance: 0.005 },
  antique_firelock: { card: 'antique_firelock_card', chance: 0.005 },
  dragon_fly: { card: 'dragon_fly_card', chance: 0.005 },
  vagabond_wolf: { card: 'vagabond_wolf_card', chance: 0.005 },
  mysteltainn: { card: 'mysteltainn_card', chance: 0.005 },
  miyabi_ningyo: { card: 'miyabi_ningyo_card', chance: 0.005 },
  stalactic_golem: { card: 'stalactic_golem_card', chance: 0.005 },
  sting: { card: 'sting_card', chance: 0.005 },
  c_tower_manager: { card: 'c_tower_manager_card', chance: 0.005 },
  shinobi: { card: 'shinobi_card', chance: 0.005 },
  baby_leopard: { card: 'baby_leopard_card', chance: 0.005 },
  archangeling: { card: 'archangeling_card', chance: 0.005 },
  assulter: { card: 'assulter_card', chance: 0.005 },
  aster: { card: 'aster_card', chance: 0.005 },
  wild_rose: { card: 'wild_rose_card', chance: 0.005 },
  wooden_golem: { card: 'wooden_golem_card', chance: 0.005 },
  wootan_shooter: { card: 'wootan_shooter_card', chance: 0.005 },
  wootan_fighter: { card: 'wootan_fighter_card', chance: 0.005 },
  eclipse: { card: 'eclipse_card', chance: 0.005 },
  shellfish: { card: 'shellfish_card', chance: 0.005 },
  geographer: { card: 'geographer_card', chance: 0.005 },
  choco: { card: 'choco_card', chance: 0.005 },
  cookie: { card: 'cookie_card', chance: 0.005 },
  whisper_boss: { card: 'whisper_boss_card', chance: 0.005 },
  toad: { card: 'toad_card', chance: 0.005 },
  parasite: { card: 'parasite_card', chance: 0.005 },
  hylozoist: { card: 'hylozoist_card', chance: 0.005 },
  dark_snake_lord: { card: 'dark_snake_lord_card', chance: 0.005 },
  heater: { card: 'heater_card', chance: 0.005 },
  waste_stove: { card: 'waste_stove_card', chance: 0.005 },
  porcellio: { card: 'porcellio_card', chance: 0.005 },
  mineral: { card: 'mineral_card', chance: 0.005 },
  mole: { card: 'mole_card', chance: 0.005 },
  kavac: { card: 'kavac_card', chance: 0.005 },
  breeze: { card: 'breeze_card', chance: 0.005 },
  tha_maero: { card: 'tha_maero_card', chance: 0.005 },
  alicel: { card: 'alicel_card', chance: 0.005 },
  hodremlin: { card: 'hodremlin_card', chance: 0.005 },
  roween: { card: 'roween_card', chance: 0.005 },
  duneyrr: { card: 'duneirre_card', chance: 0.005 },
  rata: { card: 'lata_card', chance: 0.005 },
  hardrock_mommoth: { card: 'hardrock_mommos_card', chance: 0.005 },
  leak: { card: 'leak_card', chance: 0.005 },
  kraken: { card: 'kraken_card', chance: 0.005 },
  wild_rider: { card: 'wild_rider_card', chance: 0.005 },
  alphoccio: { card: 'alphoccio_card', chance: 0.005 },
  celia: { card: 'ceila_card', chance: 0.005 },
  chen: { card: 'chen_card', chance: 0.005 },
  flamel: { card: 'flamel_card', chance: 0.005 },
  gertie: { card: 'gertie_card', chance: 0.005 },
  randel: { card: 'randel_card', chance: 0.005 },
  trentini: { card: 'trentini_card', chance: 0.005 },
  watcher: { card: 'watcher_card', chance: 0.005 },
  dr_eggring: { card: 'eggring_card', chance: 0.005 },
  dr_lunatic: { card: 'leaf_lunatic_card', chance: 0.005 },
  dr_fabre: { card: 'grass_fabre_card', chance: 0.005 },
  dr_hornet: { card: 'wild_honet_card', chance: 0.005 },
  dr_roda_frog: { card: 'sw_roda_frog_card', chance: 0.005 },
  dr_desert_wolf_b: { card: 'hunter_wolf_card', chance: 0.005 },
  dr_spore: { card: 'trance_spore_card', chance: 0.005 },
  ill_drainliar: { card: 'matt_drainliar_card', chance: 0.005 }
};
